version: "3.0"

services:
  dynamodb:
    # image: localstack/localstack:latest
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory -port 8000
    working_dir: /home/dynamodblocal
    ports:
      - "4566:8000"
