service: todo-list
frameworkVersion: "3"

package:
  exclude:
    - node_modules/**

custom:
  tableName: "tasks-table-${sls:stage}"
  dynamodb:
    stages:
      - local
    start:
      docker: true
      port: 4566
      migrate: true
      noStart: true
  output:
    file: .build/stack.json

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [TasksTable, Arn]
  environment:
    TASKS_TABLE: ${self:custom.tableName}
    API_URL: !GetAtt HttpApi.ApiEndpoint
    STAGE: "${sls:stage}"

functions:
  createTask:
    handler: task/controller.createTask
    events:
      - httpApi:
          method: POST
          path: /
  getTasks:
    handler: task/controller.getTasks
    events:
      - httpApi:
          method: GET
          path: /
resources:
  - ${file(resources/tasksTable.yml)}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-stack-output
