name: Setup and Test
description: "Checkout repo, install dependencies and run tests"
inputs:
  aws-access-key-id:
    description: "aws access key id"
    required: true
  aws-secret-access-key:
    description: "aws secret access key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      shell: bash
      run: npm install
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-central-1
    - name: Setup DynamoDB Local
      uses: rrainn/dynamodb-action@v2.0.1
      with:
        optimizeDbBeforeStartup: true
        port: 4566
        cors: "*"
    - name: Setup serverless framework server
      shell: bash
      run: npx serverless offline
    - name: Run Tests
      shell: bash
      run: npm run-script test
