name: Setup and Test
description: "Checkout repo, install dependencies and run tests"

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      shell: bash
      run: npm install
    - name: Setup DynamoDB Local
      uses: rrainn/dynamodb-action@v2.0.1
      with:
        port: 4566
        cors: "*"
    - name: Run Tests
      shell: bash
      run: npm run test
