name: Setup and Test
description: "Checkout repo, install dependencies and run tests"
inputs:
  aws-access-key-id: # id of input
    description: "aws-access-key-id"
    required: true
  aws-secret-access-key: # id of input
    description: "aws-secret-access-key"
    required: true
  branch:
    description: "branch name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      shell: bash
      run: npm install
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1
    - name: Deploy test environment
      shell: bash
      run: npm run deploy-branch --stage=pre-${{ inputs.branch }}
    - name: Extract api url from deployment info
      uses: sergeysova/jq-action@v2
      id: api_url
      with:
        cmd: "jq .HttpApiUrl .build/stack.json -r"
    - name: Run Tests
      shell: bash
      run: npm run test --stage=pre-${{ inputs.branch }} --api_url=${{ steps.api_url.outputs.value }}
    - name: Remove test environment
      shell: bash
      run: npm run undeploy-branch --stage=pre-${{ inputs.branch }}
