name: Setup and Test
description: "Checkout repo, install dependencies and run tests"

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      shell: bash
      run: npm install
    - name: Deploy test environment
      run: npm run deploy-branch --stage=pre-dev
    - name: Run Tests
      shell: bash
      run: npm run test --stage=pre-dev
