name: Deploy to Development
on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - "4566:8000"

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@master
      - name: setup-and-test
        uses: ./.github/actions/setup-and-test/
        with:
          aws-access-key-id: fake
          aws-secret-access-key: fake

  deploy:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@master
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Serverless Deploy
        run: npm run-script deploy-dev
