name: Deploy to Production
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      dynamodb:
        # Docker Hub image
        image: localstack/localstack:latest
        environment:
          - AWS_DEFAULT_REGION=ap-southeast-1
          - EDGE_PORT=4566
          - SERVICES=dynamodb
        ports:
          - 4566:4566

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@master
      - name: setup-and-test
        uses: ./.github/actions/setup-and-test/
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Serverless Deploy
        run: npm run-script deploy-dev
