name: deploy-aws-lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@master
      - name: setup-and-test
        uses: ./.github/actions/setup-and-test/
      - name: Serverless Deploy
        run: npm run-script deploy
